In [2]:
import pandas as pd
import xlrd
import openpyxl
import numpy as np

In [3]:
xls = pd.ExcelFile('Experiment_22.xlsx')

In [4]:
print(xls)

In [5]:
df = xls.parse('Sheet1')

In [6]:
print(df)

               Name  Maths  Science
0     Aarfa Hussain     17       18
1         Akira Rai     20       19
2       Alizeh Khan     20       11
3    Anushka Sharma     19       20
4   Bijilee Mandola     14       15
5      Bulbul Singh     13       15
6         Farah Ali     14       14
7      Ishika Desai     15        1
8      Jagat Janini     19        3
9             Mamta     17        5
10            Meera     18       14
11    Rosie Noronha     16        8
12         Rukhsana     14       15
13     Sejal Zaveri     10       16
14    Shashi Kumari      2        1
15    Shruti Kakkar      5        4
16   Simran Chaggal     11       12
17     Taani Sahini     10       10
18      Winnie Diaz     15       15


In [7]:
marks = np.array(df['Maths'])
print(marks)

[17 20 20 19 14 13 14 15 19 17 18 16 14 10  2  5 11 10 15]


In [8]:
print("Average marks in maths :       ", marks.mean())
print("Minimum marks in maths:    ", marks.min())
print("Maximum marks in maths:    ", marks.max())

Average marks in maths :        14.157894736842104
Minimum marks in maths:     2
Maximum marks in maths:     20


In [9]:
maths = np.array(df['Maths'])

science = np.array(df['Science'])




In [10]:
maths

array([17, 20, 20, 19, 14, 13, 14, 15, 19, 17, 18, 16, 14, 10,  2,  5, 11,
       10, 15], dtype=int64)

In [11]:
science

array([18, 19, 11, 20, 15, 15, 14,  1,  3,  5, 14,  8, 15, 16,  1,  4, 12,
       10, 15], dtype=int64)

In [12]:
maths+science

array([35, 39, 31, 39, 29, 28, 28, 16, 22, 22, 32, 24, 29, 26,  3,  9, 23,
       20, 30], dtype=int64)

In [13]:
sum_of_marks=df["Maths"] + df["Science"]
df['Sum']= sum_of_marks

In [14]:
df['Sum']

0     35
1     39
2     31
3     39
4     29
5     28
6     28
7     16
8     22
9     22
10    32
11    24
12    29
13    26
14     3
15     9
16    23
17    20
18    30
Name: Sum, dtype: int64

In [15]:
df.head()

Name  Maths  Science  Sum
0    Aarfa Hussain     17       18   35
1        Akira Rai     20       19   39
2      Alizeh Khan     20       11   31
3   Anushka Sharma     19       20   39
4  Bijilee Mandola     14       15   29

In [16]:
df[['Maths']].idxmin()

Maths    14
dtype: int64

In [17]:
df[['Maths']].idxmax()

Maths    1
dtype: int64

In [18]:
df[['Maths']].min()

Maths    2
dtype: int64

In [19]:
Minimum_maths_score = [df[['Maths']].idxmin(),df[['Maths']].min()]

In [20]:
Minimum_maths_score 

[Maths    14
 dtype: int64,
 Maths    2
 dtype: int64]

In [21]:
df['Maths'].sum()

269

In [22]:
df['Science'].sum()

216

In [23]:
df['Maths'].min()

2

In [24]:
df['Science'].min()

1

In [25]:
df['Science'].idxmax()

3

In [26]:
df['Maths'].mean()

14.157894736842104

In [27]:
df['Science'].mean()

11.368421052631579

In [28]:
df['Science'].value_counts()

15    4
1     2
14    2
3     1
4     1
5     1
8     1
10    1
11    1
12    1
16    1
18    1
19    1
20    1
Name: Science, dtype: int64

In [29]:
df['Maths'].value_counts()

14    3
10    2
15    2
17    2
19    2
20    2
2     1
5     1
11    1
13    1
16    1
18    1
Name: Maths, dtype: int64

In [30]:
df['Science'].unique()

array([18, 19, 11, 20, 15, 14,  1,  3,  5,  8, 16,  4, 12, 10],
      dtype=int64)

In [31]:
df['Maths'].unique()

array([17, 20, 19, 14, 13, 15, 18, 16, 10,  2,  5, 11], dtype=int64)

In [32]:
df.pivot_table(index=['Maths'], aggfunc='size')

Maths
2     1
5     1
10    2
11    1
13    1
14    3
15    2
16    1
17    2
18    1
19    2
20    2
dtype: int64

In [33]:
pivot_agg = pd.pivot_table(df,index=['Science','Maths'], values = ['Sum'], aggfunc=[np.sum])

In [34]:
pivot_agg


sum
              Sum
Science Maths    
1       2       3
        15     16
3       19     22
4       5       9
5       17     22
8       16     24
10      10     20
11      20     31
12      11     23
14      14     28
        18     32
15      13     28
        14     58
        15     30
16      10     26
18      17     35
19      20     39
20      19     39

In [35]:
df.describe()

Maths    Science        Sum
count  19.000000  19.000000  19.000000
mean   14.157895  11.368421  25.526316
std     4.879244   6.048053   9.179497
min     2.000000   1.000000   3.000000
25%    12.000000   6.500000  22.000000
50%    15.000000  14.000000  28.000000
75%    17.500000  15.000000  30.500000
max    20.000000  20.000000  39.000000

In [37]:
df.dtypes

Name       object
Maths       int64
Science     int64
Sum         int64
dtype: object

In [38]:
df.columns

Index(['Name', 'Maths', 'Science', 'Sum'], dtype='object')

In [39]:
df.count(axis=0)

Name       19
Maths      19
Science    19
Sum        19
dtype: int64

In [40]:
df.sum(axis=0)

Name       Aarfa HussainAkira RaiAlizeh KhanAnushka Sharm...
Maths                                                    269
Science                                                  216
Sum                                                      485
dtype: object

In [41]:
df.info

<bound method DataFrame.info of                Name  Maths  Science  Sum
0     Aarfa Hussain     17       18   35
1         Akira Rai     20       19   39
2       Alizeh Khan     20       11   31
3    Anushka Sharma     19       20   39
4   Bijilee Mandola     14       15   29
5      Bulbul Singh     13       15   28
6         Farah Ali     14       14   28
7      Ishika Desai     15        1   16
8      Jagat Janini     19        3   22
9             Mamta     17        5   22
10            Meera     18       14   32
11    Rosie Noronha     16        8   24
12         Rukhsana     14       15   29
13     Sejal Zaveri     10       16   26
14    Shashi Kumari      2        1    3
15    Shruti Kakkar      5        4    9
16   Simran Chaggal     11       12   23
17     Taani Sahini     10       10   20
18      Winnie Diaz     15       15   30>

In [42]:
df.tail

<bound method NDFrame.tail of                Name  Maths  Science  Sum
0     Aarfa Hussain     17       18   35
1         Akira Rai     20       19   39
2       Alizeh Khan     20       11   31
3    Anushka Sharma     19       20   39
4   Bijilee Mandola     14       15   29
5      Bulbul Singh     13       15   28
6         Farah Ali     14       14   28
7      Ishika Desai     15        1   16
8      Jagat Janini     19        3   22
9             Mamta     17        5   22
10            Meera     18       14   32
11    Rosie Noronha     16        8   24
12         Rukhsana     14       15   29
13     Sejal Zaveri     10       16   26
14    Shashi Kumari      2        1    3
15    Shruti Kakkar      5        4    9
16   Simran Chaggal     11       12   23
17     Taani Sahini     10       10   20
18      Winnie Diaz     15       15   30>

In [43]:
df.mean(axis=0)

Maths      14.157895
Science    11.368421
Sum        25.526316
dtype: float64

In [44]:
df.max(axis=0)

Name       Winnie Diaz
Maths               20
Science             20
Sum                 39
dtype: object

In [45]:
df.median(axis=0)

Maths      15.0
Science    14.0
Sum        28.0
dtype: float64

In [50]:
df['Maths'].mean()

14.157894736842104

In [51]:
df['Science'].mean()

11.368421052631579

In [52]:
df['Maths'].sum()

269

In [53]:
df['Science'].sum()

216

In [54]:
df['Maths'].min()

2

In [55]:
df['Maths'].max()

20

In [57]:
df['Science'].min()

1

In [58]:
df['Science'].max()

20